Mark Unity version as required
Dinomite-Studios/unity-azure-pipelines-tasks pull request #234
Opened 2023-06-12 10:35 UTC by IanMoroney

To avoid `Path` [issues](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/219), the unity version should be specified and marked as a required input.

2023-06-20 22:30 UTC, o-litnon requested changes

2023-06-20 22:30 UTC, o-litnon commented on Tasks/UnityTest/UnityTestV1/task.json
>        "helpMarkDown": "(Optional) Enter the custom version of Unity. If no value is entered, it will be resolved automatically."
Can you update the markdown comment?

2023-06-20 22:32 UTC, o-litnon commented on Tasks/UnityTest/UnityTestV1/task.json
>        "helpMarkDown": "(Optional) Enter the custom version of Unity. If no value is entered, it will be resolved automatically."
```suggestion
      "helpMarkDown": "Enter the custom version of Unity"
```

2023-07-07 09:49 UTC, FejZa commented
Let me look into this. It does not make sense to make something sound "mandatory", when it isn't.

2024-02-06 10:35 UTC, merged